version: "3.8"

services:
  app:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - wiremock
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
    command: npm run dev
    networks:
      - app-network

  wiremock:
    image: wiremock/wiremock:2.35.0
    ports:
      - "8080:8080"
    volumes:
      - ./wiremock:/home/wiremock
    command: --verbose
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
